[package]
name = "desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Native desktop runner for the Serverless & Desktop Leptos Template powered by Tauri v2"

[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
app = { workspace = true, features = ["csr"] }
leptos = { workspace = true, features = ["csr"] }
shared = { workspace = true }
mimalloc = "0.1"
spodeian-telemetry = { workspace = true }
